Program -> Elements
Elements -> Elements Element
Elements -> Element
Element -> FunctionDecl
Element -> StructDecl
Element -> Statement
StructDecl -> KW_STRUCT ID LBRACE Fields RBRACE
Fields -> FieldList
Fields -> 
FieldList -> FieldList OptionalComma Field
FieldList -> Field
OptionalComma -> COMMA
OptionalComma -> 
Field -> ID COLON Type
FunctionDecl -> KW_FN ID LPAREN Params RPAREN OptionalReturnType Block
OptionalReturnType -> ARROW Type
OptionalReturnType -> 
Params -> ParamList
Params -> 
ParamList -> ParamList COMMA Param
ParamList -> Param
Param -> ID COLON Type
Type -> ID
Type -> LBRACKET Type RBRACKET
Type -> AMP Type
Type -> AMP LBRACKET Type RBRACKET
Block -> LBRACE Statements RBRACE
Statements -> Statements Statement
Statements -> Statement
Statements -> 
Statement -> KW_LET OptionalMut ID COLON Type Initializer SEMI
Statement -> KW_LET OptionalMut ID COLON Type SEMI
Statement -> Expr EQ Expr SEMI
Statement -> KW_RETURN Expr SEMI
Statement -> KW_RETURN SEMI
Statement -> KW_IF LPAREN Expr RPAREN Block OptionalElse
Statement -> KW_WHILE LPAREN Expr RPAREN Block
Statement -> Expr SEMI
Statement -> Block
OptionalMut -> KW_MUT
OptionalMut -> 
Initializer -> EQ Expr
Initializer -> 
OptionalElse -> KW_ELSE Block
OptionalElse -> 
Expr -> ExprOr
ExprOr -> ExprOr PIPEPIPE ExprAnd
ExprOr -> ExprAnd
ExprAnd -> ExprAnd AMPAMP ExprCmp
ExprAnd -> ExprCmp
ExprCmp -> ExprAdd EQEQ ExprAdd
ExprCmp -> ExprAdd BANGEQ ExprAdd
ExprCmp -> ExprAdd LT ExprAdd
ExprCmp -> ExprAdd LE ExprAdd
ExprCmp -> ExprAdd GT ExprAdd
ExprCmp -> ExprAdd GE ExprAdd
ExprCmp -> ExprAdd
ExprAdd -> ExprAdd PLUS ExprMul
ExprAdd -> ExprAdd MINUS ExprMul
ExprAdd -> ExprMul
ExprMul -> ExprMul STAR ExprUnary
ExprMul -> ExprMul SLASH ExprUnary
ExprMul -> ExprMul PERCENT ExprUnary
ExprMul -> ExprUnary
ExprUnary -> BANG ExprUnary
ExprUnary -> MINUS ExprUnary
ExprUnary -> ExprPrimary
ExprPrimary -> ExprPrimary DOT ID
ExprPrimary -> ExprPrimary KW_AS Type
ExprPrimary -> ExprPrimary LBRACKET Expr RBRACKET
ExprPrimary -> LPAREN Expr RPAREN
ExprPrimary -> ID
ExprPrimary -> LIT_INT_DEC
ExprPrimary -> LIT_FLOAT
ExprPrimary -> LIT_STRING
ExprPrimary -> Call
Call -> ID LPAREN Args RPAREN
Args -> ArgList
Args -> 
ArgList -> ArgList COMMA Expr
ArgList -> Expr
