/* RustLexerTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. RustLexerTokenManager.java */
import java.io.*;
import java.lang.reflect.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class RustLexerTokenManager implements RustLexerConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_1(){
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x100L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(1, 8);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x80L) != 0L || (active1 & 0x200000400000000L) != 0L)
            return 0;
         if ((active0 & 0x6000000002000L) != 0L)
         {
            jjmatchedKind = 83;
            return 99;
         }
         if ((active0 & 0xfff9fff3ffffdc00L) != 0L || (active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 83;
            return 28;
         }
         if ((active0 & 0xc00000000L) != 0L || (active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 83;
            return 152;
         }
         return -1;
      case 1:
         if ((active0 & 0xfff7fffffabfd000L) != 0L || (active1 & 0x3L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 83;
               jjmatchedPos = 1;
            }
            return 28;
         }
         if ((active0 & 0x2000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 83;
               jjmatchedPos = 1;
            }
            return 129;
         }
         if ((active0 & 0x8000005400c00L) != 0L)
            return 28;
         return -1;
      case 2:
         if ((active0 & 0x224200748820000L) != 0L || (active1 & 0x2L) != 0L)
            return 28;
         if ((active0 & 0xfdd3dff8b23df800L) != 0L || (active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 2;
            return 28;
         }
         return -1;
      case 3:
         if ((active0 & 0x5000c30920c0000L) != 0L || (active1 & 0x1L) != 0L)
            return 28;
         if ((active0 & 0xf8d3d3c82031f800L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 83;
               jjmatchedPos = 3;
            }
            return 28;
         }
         return -1;
      case 4:
         if ((active0 & 0x1c8310c800108000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 83;
               jjmatchedPos = 4;
            }
            return 28;
         }
         if ((active0 & 0xe050c30020217800L) != 0L)
            return 28;
         return -1;
      case 5:
         if ((active0 & 0x40210c800100000L) != 0L)
            return 28;
         if ((active0 & 0x9881000000008000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 5;
            return 28;
         }
         return -1;
      case 6:
         if ((active0 & 0x1800000000000000L) != 0L)
            return 28;
         if ((active0 & 0x8081000000008000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 6;
            return 28;
         }
         return -1;
      case 7:
         if ((active0 & 0x81000000008000L) != 0L)
            return 28;
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 7;
            return 28;
         }
         return -1;
      case 8:
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 8;
            return 28;
         }
         return -1;
      case 9:
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 9;
            return 28;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 13:
         jjmatchedKind = 4;
         return jjMoveStringLiteralDfa1_0(0x20L, 0x0L);
      case 33:
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000L);
      case 35:
         return jjStopAtPos(0, 110);
      case 36:
         return jjStopAtPos(0, 111);
      case 37:
         jjmatchedKind = 112;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000L);
      case 38:
         jjmatchedKind = 113;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x18000000L);
      case 40:
         return jjStopAtPos(0, 114);
      case 41:
         return jjStopAtPos(0, 115);
      case 42:
         jjmatchedKind = 116;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000L);
      case 43:
         jjmatchedKind = 117;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000000L);
      case 44:
         return jjStopAtPos(0, 118);
      case 45:
         jjmatchedKind = 119;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180000000L);
      case 46:
         jjmatchedKind = 120;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200600000L);
      case 47:
         jjmatchedKind = 121;
         return jjMoveStringLiteralDfa1_0(0x80L, 0x400000000L);
      case 58:
         jjmatchedKind = 122;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000L);
      case 59:
         return jjStopAtPos(0, 123);
      case 60:
         jjmatchedKind = 124;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3000800000L);
      case 61:
         jjmatchedKind = 125;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc000000000L);
      case 62:
         jjmatchedKind = 126;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x30001000000L);
      case 63:
         return jjStopAtPos(0, 127);
      case 64:
         return jjStopAtPos(0, 128);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x2000000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 129);
      case 92:
         return jjStopAtPos(0, 130);
      case 93:
         return jjStopAtPos(0, 131);
      case 94:
         jjmatchedKind = 132;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000000000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x1000000001c00L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x6000000002000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1c000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x8000000020000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x1c0000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x10000000e00000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x20000000000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x7000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x18000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x80400001e0000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x100000200000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0xc00000000L, 0x2L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1d000000000L, 0x1L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x6000e0000000000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x4800300000000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0xc00000000000L, 0x0L);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 133);
      case 124:
         jjmatchedKind = 134;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180000000000L);
      case 125:
         return jjStopAtPos(0, 135);
      case 126:
         return jjStopAtPos(0, 136);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, 0L);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         break;
      case 38:
         if ((active1 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 91);
         break;
      case 42:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      case 46:
         if ((active1 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 97;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x600000L);
      case 58:
         if ((active1 & 0x800000000L) != 0L)
            return jjStopAtPos(1, 99);
         break;
      case 60:
         if ((active1 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000L);
      case 61:
         if ((active1 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 89);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 90);
         else if ((active1 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 92);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 93);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStopAtPos(1, 94);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStopAtPos(1, 95);
         else if ((active1 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 98);
         else if ((active1 & 0x2000000000L) != 0L)
            return jjStopAtPos(1, 101);
         else if ((active1 & 0x4000000000L) != 0L)
            return jjStopAtPos(1, 102);
         else if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 104);
         else if ((active1 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 106);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 107);
         break;
      case 62:
         if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 96);
         else if ((active1 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 103);
         else if ((active1 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 105;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8040000020200000L, active1, 0x3L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x22003c08000000L, active1, 0L);
      case 102:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(1, 24, 28);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0xc00000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x3010000000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L, active1, 0L);
      case 110:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(1, 22, 28);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(1, 26, 28);
         return jjMoveStringLiteralDfa2_0(active0, 0x4800100000080000L, active1, 0L);
      case 111:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 51, 28);
         return jjMoveStringLiteralDfa2_0(active0, 0x40000d080c000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x300060000012000L, active1, 0L);
      case 115:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000800L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0xc000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x10300000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x400080000020000L, active1, 0L);
      case 124:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 108);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active1 & 0x200000L) != 0L)
            return jjStopAtPos(2, 85);
         break;
      case 61:
         if ((active1 & 0x400000L) != 0L)
            return jjStopAtPos(2, 86);
         else if ((active1 & 0x800000L) != 0L)
            return jjStopAtPos(2, 87);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStopAtPos(2, 88);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x24000011000L, active1, 0L);
      case 98:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(2, 33, 28);
         break;
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x8042000000000000L, active1, 0L);
      case 100:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(2, 30, 28);
         break;
      case 101:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 45, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x2080400000002000L, active1, 0L);
      case 102:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(2, 34, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4100800000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000200000L, active1, 0L);
      case 110:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 17, 28);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 53, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000c000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x400090002000000L, active1, 0L);
      case 114:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000008000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x801100000040000L, active1, 0L);
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(2, 27, 28);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(2, 32, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x820100000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000080000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L, active1, 0L);
      case 119:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 65, 28);
         break;
      case 120:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 50, 28);
         break;
      case 121:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 57, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x800L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x10100000002000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L, active1, 0L);
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 28);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 31, 28);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 28);
         else if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(3, 64, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x400010000100000L, active1, 0L);
      case 102:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 28);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 28);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x800020000001000L, active1, 0L);
      case 108:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x2000800000000000L, active1, 0L);
      case 109:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 28);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x4002000000000000L, active1, 0L);
      case 112:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 28);
         break;
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x80c0400000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x204000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x1001004000018000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x8800000000L, active1, 0L);
      case 118:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 56, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 28);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 100:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 61, 28);
         break;
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 28);
         else if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 28);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 46, 28);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 47, 28);
         break;
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L);
      case 104:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 28);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000008000L);
      case 107:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 13, 28);
         break;
      case 108:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 52, 28);
         break;
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000L);
      case 110:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 62, 28);
         break;
      case 111:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x8400000000000000L);
      case 114:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 40, 28);
         return jjMoveStringLiteralDfa5_0(active0, 0x81000800100000L);
      case 116:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 28);
         else if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 28);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 41, 28);
         break;
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000000L);
      case 122:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x1001000000000000L);
      case 99:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 28);
         break;
      case 101:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 44, 28);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 49, 28);
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000000L);
      case 102:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 58, 28);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000000L);
      case 110:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 20, 28);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 35, 28);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 116:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 39, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L);
      case 100:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 59, 28);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000000L);
      case 108:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 60, 28);
         break;
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 15, 28);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 55, 28);
         break;
      case 116:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 48, 28);
         break;
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 63, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 174;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 99:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 83)
                        kind = 83;
                     { jjCheckNAdd(28); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddStates(0, 3); }
                  else if (curChar == 39)
                     { jjAddStates(4, 5); }
                  break;
               case 129:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 83)
                        kind = 83;
                     { jjCheckNAdd(28); }
                  }
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 148;
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(130, 131); }
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 70)
                        kind = 70;
                     { jjCheckNAddStates(6, 13); }
                  }
                  else if (curChar == 39)
                     { jjAddStates(14, 16); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(17, 20); }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 0;
                  if (curChar == 48)
                     { jjAddStates(21, 23); }
                  break;
               case 152:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 83)
                        kind = 83;
                     { jjCheckNAdd(28); }
                  }
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 172;
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(153, 154); }
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 169;
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 0:
                  if (curChar != 47)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAddStates(24, 26); }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAddStates(24, 26); }
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
               case 25:
                  if (curChar == 34)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 7:
                  if ((0xfffffffbffffdfffL & l) != 0L)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 9:
                  if (curChar == 10)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 10:
                  if (curChar == 34 && kind > 75)
                     kind = 75;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjAddStates(27, 29); }
                  break;
               case 18:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 20:
                  if (curChar == 48)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 26:
                  if (curChar == 39)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  { jjCheckNAdd(28); }
                  break;
               case 29:
                  if (curChar == 48)
                     { jjAddStates(21, 23); }
                  break;
               case 32:
               case 33:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddTwoStates(33, 34); }
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 38:
               case 39:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjCheckNAddTwoStates(39, 40); }
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 44:
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  { jjCheckNAddStates(6, 13); }
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(49, 50); }
                  break;
               case 50:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(52, 53); }
                  break;
               case 54:
                  if ((0x280000000000L & l) != 0L)
                     { jjAddStates(30, 31); }
                  break;
               case 56:
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(57, 58); }
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(60, 61); }
                  break;
               case 61:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
               case 63:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(63, 64); }
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(66, 67); }
                  break;
               case 68:
                  if ((0x280000000000L & l) != 0L)
                     { jjAddStates(32, 33); }
                  break;
               case 70:
               case 71:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(71, 72); }
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  { jjCheckNAddTwoStates(74, 75); }
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 77:
                  if (curChar == 39)
                     { jjAddStates(14, 16); }
                  break;
               case 78:
                  if ((0xffffff7fffffd9ffL & l) != 0L)
                     { jjCheckNAdd(79); }
                  break;
               case 79:
                  if (curChar == 39 && kind > 74)
                     kind = 74;
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjAddStates(34, 36); }
                  break;
               case 89:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(79); }
                  break;
               case 91:
                  if (curChar == 48)
                     { jjCheckNAdd(79); }
                  break;
               case 96:
                  if (curChar == 34)
                     { jjCheckNAdd(79); }
                  break;
               case 97:
                  if (curChar == 39)
                     { jjCheckNAdd(79); }
                  break;
               case 100:
                  if ((0xffffff7fffffd9ffL & l) != 0L)
                     { jjCheckNAdd(102); }
                  break;
               case 101:
                  if (curChar == 39 && kind > 77)
                     kind = 77;
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 106:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(102); }
                  break;
               case 107:
                  if (curChar == 48)
                     { jjCheckNAdd(102); }
                  break;
               case 112:
                  if (curChar == 34)
                     { jjCheckNAdd(102); }
                  break;
               case 113:
                  if (curChar == 39)
                     { jjCheckNAdd(102); }
                  break;
               case 114:
                  if (curChar == 34)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 115:
                  if ((0xfffffffbffffdfffL & l) != 0L)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 117:
                  if (curChar == 10)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 118:
                  if (curChar == 34 && kind > 78)
                     kind = 78;
                  break;
               case 121:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 122:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 123:
                  if (curChar == 48)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 128:
                  if (curChar == 39)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 130:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(130, 131); }
                  break;
               case 131:
                  if (curChar == 34 && kind > 81)
                     kind = 81;
                  break;
               case 133:
                  if (curChar == 34)
                     { jjCheckNAddStates(37, 39); }
                  break;
               case 134:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(37, 39); }
                  break;
               case 135:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 136:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     { jjCheckNAddStates(37, 39); }
                  break;
               case 137:
                  if (curChar == 35 && kind > 81)
                     kind = 81;
                  break;
               case 138:
                  if (curChar == 34)
                     { jjCheckNAdd(137); }
                  break;
               case 139:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 141:
                  if (curChar == 34)
                     { jjCheckNAddStates(40, 42); }
                  break;
               case 142:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(40, 42); }
                  break;
               case 143:
                  if (curChar == 34)
                     { jjCheckNAdd(144); }
                  break;
               case 144:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     { jjCheckNAddStates(40, 42); }
                  break;
               case 145:
                  if (curChar == 34)
                     { jjAddStates(43, 44); }
                  break;
               case 146:
                  if (curChar == 35)
                     { jjCheckNAdd(144); }
                  break;
               case 147:
                  if (curChar == 35)
                     { jjCheckNAdd(137); }
                  break;
               case 148:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 149:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 153:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(153, 154); }
                  break;
               case 154:
                  if (curChar == 34 && kind > 80)
                     kind = 80;
                  break;
               case 155:
                  if (curChar == 34)
                     { jjCheckNAddStates(45, 47); }
                  break;
               case 156:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(45, 47); }
                  break;
               case 157:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 158:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     { jjCheckNAddStates(45, 47); }
                  break;
               case 159:
                  if (curChar == 35 && kind > 80)
                     kind = 80;
                  break;
               case 160:
                  if (curChar == 34)
                     { jjCheckNAdd(159); }
                  break;
               case 161:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 162:
                  if (curChar == 34)
                     { jjCheckNAddStates(48, 50); }
                  break;
               case 163:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(48, 50); }
                  break;
               case 164:
                  if (curChar == 34)
                     { jjCheckNAdd(165); }
                  break;
               case 165:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     { jjCheckNAddStates(48, 50); }
                  break;
               case 166:
                  if (curChar == 34)
                     { jjAddStates(51, 52); }
                  break;
               case 167:
                  if (curChar == 35)
                     { jjCheckNAdd(165); }
                  break;
               case 168:
                  if (curChar == 35)
                     { jjCheckNAdd(159); }
                  break;
               case 169:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 170:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 173:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 84)
                     kind = 84;
                  jjstateSet[jjnewStateCnt++] = 173;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 99:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 83)
                        kind = 83;
                     { jjCheckNAdd(28); }
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 149;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 139;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 129:
               case 28:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  { jjCheckNAdd(28); }
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 83)
                        kind = 83;
                     { jjCheckNAdd(28); }
                  }
                  if (curChar == 114)
                     { jjAddStates(53, 56); }
                  else if (curChar == 98)
                     { jjCheckNAddStates(57, 61); }
                  break;
               case 152:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  { jjCheckNAdd(28); }
                  break;
               case 1:
                  if (kind > 6)
                     kind = 6;
                  { jjAddStates(24, 26); }
                  break;
               case 7:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 8:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 92)
                     { jjAddStates(62, 70); }
                  break;
               case 12:
                  if (curChar == 123)
                     { jjCheckNAdd(13); }
                  break;
               case 13:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 14:
                  if (curChar == 95)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 15:
                  if (curChar == 125)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 16:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 17:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 19:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 21:
                  if (curChar == 116)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 22:
                  if (curChar == 114)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 23:
                  if (curChar == 110)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 24:
                  if (curChar == 92)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 27:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 83)
                     kind = 83;
                  { jjCheckNAdd(28); }
                  break;
               case 30:
                  if (curChar == 98)
                     { jjCheckNAddTwoStates(31, 32); }
                  break;
               case 31:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(31, 32); }
                  break;
               case 33:
                  if (curChar != 95)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjAddStates(71, 72); }
                  break;
               case 34:
               case 35:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAdd(35); }
                  break;
               case 36:
                  if (curChar == 111)
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 37:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 39:
                  if (curChar != 95)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjAddStates(73, 74); }
                  break;
               case 40:
               case 41:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjCheckNAdd(41); }
                  break;
               case 42:
                  if (curChar == 120)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 43:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 44:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 45:
                  if ((0x7e8000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 46:
               case 47:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  { jjCheckNAdd(47); }
                  break;
               case 49:
                  if (curChar == 95)
                     { jjAddStates(75, 76); }
                  break;
               case 52:
                  if (curChar == 95)
                     { jjAddStates(77, 78); }
                  break;
               case 53:
                  if ((0x2000000020L & l) != 0L)
                     { jjCheckNAddStates(79, 81); }
                  break;
               case 55:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(55, 56); }
                  break;
               case 57:
                  if (curChar != 95)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjAddStates(82, 83); }
                  break;
               case 58:
               case 59:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAdd(59); }
                  break;
               case 60:
                  if (curChar == 95)
                     { jjAddStates(84, 85); }
                  break;
               case 63:
                  if (curChar != 95)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjAddStates(86, 87); }
                  break;
               case 64:
               case 65:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAdd(65); }
                  break;
               case 66:
                  if (curChar == 95)
                     { jjAddStates(88, 89); }
                  break;
               case 67:
                  if ((0x2000000020L & l) != 0L)
                     { jjCheckNAddStates(90, 92); }
                  break;
               case 69:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(69, 70); }
                  break;
               case 71:
                  if (curChar != 95)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjAddStates(93, 94); }
                  break;
               case 72:
               case 73:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAdd(73); }
                  break;
               case 74:
                  if (curChar != 95)
                     break;
                  if (kind > 70)
                     kind = 70;
                  { jjAddStates(95, 96); }
                  break;
               case 75:
               case 76:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  { jjCheckNAdd(76); }
                  break;
               case 78:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAdd(79); }
                  break;
               case 80:
               case 81:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  { jjCheckNAdd(81); }
                  break;
               case 82:
                  if (curChar == 92)
                     { jjAddStates(97, 105); }
                  break;
               case 83:
                  if (curChar == 123)
                     { jjCheckNAdd(84); }
                  break;
               case 84:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(34, 36); }
                  break;
               case 85:
                  if (curChar == 95)
                     { jjCheckNAddStates(34, 36); }
                  break;
               case 86:
                  if (curChar == 125)
                     { jjCheckNAdd(79); }
                  break;
               case 87:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 88:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 90:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAdd(79); }
                  break;
               case 92:
                  if (curChar == 116)
                     { jjCheckNAdd(79); }
                  break;
               case 93:
                  if (curChar == 114)
                     { jjCheckNAdd(79); }
                  break;
               case 94:
                  if (curChar == 110)
                     { jjCheckNAdd(79); }
                  break;
               case 95:
                  if (curChar == 92)
                     { jjCheckNAdd(79); }
                  break;
               case 98:
                  if (curChar == 98)
                     { jjCheckNAddStates(57, 61); }
                  break;
               case 100:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAdd(102); }
                  break;
               case 102:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 92)
                     { jjAddStates(106, 113); }
                  break;
               case 104:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 105:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 106:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAdd(102); }
                  break;
               case 108:
                  if (curChar == 116)
                     { jjCheckNAdd(102); }
                  break;
               case 109:
                  if (curChar == 114)
                     { jjCheckNAdd(102); }
                  break;
               case 110:
                  if (curChar == 110)
                     { jjCheckNAdd(102); }
                  break;
               case 111:
                  if (curChar == 92)
                     { jjCheckNAdd(102); }
                  break;
               case 115:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 116:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 92)
                     { jjCheckNAddStates(114, 121); }
                  break;
               case 120:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 121:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 122:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 124:
                  if (curChar == 116)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 125:
                  if (curChar == 114)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 126:
                  if (curChar == 110)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 127:
                  if (curChar == 92)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 130:
                  { jjAddStates(122, 123); }
                  break;
               case 132:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 134:
               case 136:
                  { jjCheckNAddStates(37, 39); }
                  break;
               case 140:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 142:
               case 144:
                  { jjCheckNAddStates(40, 42); }
                  break;
               case 150:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 114)
                     { jjAddStates(53, 56); }
                  break;
               case 153:
                  { jjAddStates(124, 125); }
                  break;
               case 156:
               case 158:
                  { jjCheckNAddStates(45, 47); }
                  break;
               case 163:
               case 165:
                  { jjCheckNAddStates(48, 50); }
                  break;
               case 172:
               case 173:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 84)
                     kind = 84;
                  { jjCheckNAdd(173); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjAddStates(24, 26); }
                  break;
               case 7:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(17, 20); }
                  break;
               case 78:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 100:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 115:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(0, 3); }
                  break;
               case 130:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(122, 123); }
                  break;
               case 134:
               case 136:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(37, 39); }
                  break;
               case 142:
               case 144:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(40, 42); }
                  break;
               case 153:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(124, 125); }
                  break;
               case 156:
               case 158:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(45, 47); }
                  break;
               case 163:
               case 165:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(48, 50); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 174 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, "\141\163", 
"\141\163\171\156\143", "\141\167\141\151\164", "\142\162\145\141\153", "\143\157\156\163\164", 
"\143\157\156\164\151\156\165\145", "\143\162\141\164\145", "\144\171\156", "\145\154\163\145", 
"\145\156\165\155", "\145\170\164\145\162\156", "\146\141\154\163\145", "\146\156", 
"\146\157\162", "\151\146", "\151\155\160\154", "\151\156", "\154\145\164", 
"\154\157\157\160", "\155\141\164\143\150", "\155\157\144", "\155\157\166\145", "\155\165\164", 
"\160\165\142", "\162\145\146", "\162\145\164\165\162\156", "\163\145\154\146", 
"\123\145\154\146", "\163\164\141\164\151\143", "\163\164\162\165\143\164", 
"\163\165\160\145\162", "\164\162\141\151\164", "\164\162\165\145", "\164\171\160\145", 
"\165\156\163\141\146\145", "\165\163\145", "\167\150\145\162\145", "\167\150\151\154\145", 
"\141\142\163\164\162\141\143\164", "\142\145\143\157\155\145", "\142\157\170", "\144\157", 
"\146\151\156\141\154", "\147\145\156", "\155\141\143\162\157", "\157\166\145\162\162\151\144\145", 
"\160\162\151\166", "\164\162\171", "\164\171\160\145\157\146", "\165\156\163\151\172\145\144", 
"\166\151\162\164\165\141\154", "\171\151\145\154\144", "\165\156\151\157\156", 
"\155\141\143\162\157\137\162\165\154\145\163", "\163\141\146\145", "\162\141\167", null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, "\56\56\56", 
"\56\56\75", "\74\74\75", "\76\76\75", "\41\75", "\45\75", "\46\46", "\46\75", "\52\75", 
"\53\75", "\55\75", "\55\76", "\56\56", "\57\75", "\72\72", "\74\74", "\74\75", 
"\75\75", "\75\76", "\76\75", "\76\76", "\136\75", "\174\75", "\174\174", "\41", "\43", 
"\44", "\45", "\46", "\50", "\51", "\52", "\53", "\54", "\55", "\56", "\57", "\72", 
"\73", "\74", "\75", "\76", "\77", "\100", "\133", "\134", "\135", "\136", "\173", 
"\174", "\175", "\176", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   115, 116, 118, 119, 100, 103, 49, 50, 60, 61, 66, 67, 74, 75, 78, 80, 
   82, 7, 8, 10, 11, 30, 36, 42, 1, 2, 4, 13, 14, 15, 55, 56, 
   69, 70, 84, 85, 86, 134, 135, 138, 142, 143, 145, 146, 147, 156, 157, 160, 
   163, 164, 166, 167, 168, 152, 161, 170, 171, 99, 114, 132, 140, 150, 16, 17, 
   20, 21, 22, 23, 24, 25, 26, 33, 34, 39, 40, 49, 50, 52, 53, 54, 
   55, 56, 57, 58, 60, 61, 63, 64, 66, 67, 68, 69, 70, 71, 72, 74, 
   75, 87, 88, 91, 92, 93, 94, 95, 96, 97, 104, 107, 108, 109, 110, 111, 
   112, 113, 120, 123, 124, 125, 126, 127, 114, 128, 130, 131, 153, 154, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (java.io.IOException e1) { continue EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 9)
         {
            jjmatchedKind = 9;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        jjimageLen += jjmatchedPos + 1;
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public RustLexerTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public RustLexerTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 174; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_BLOCK_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffffffc01L, 0xffffffffffff6c7fL, 0x1ffL, 
};
static final long[] jjtoSkip = {
   0x17eL, 0x0L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x140L, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x280L, 0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[174];
    private final int[] jjstateSet = new int[2 * 174];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
