/* Generated By:JavaCC: Do not edit this line. RustLexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RustLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 8;
  /** RegularExpression Id. */
  int KW_AS = 10;
  /** RegularExpression Id. */
  int KW_ASYNC = 11;
  /** RegularExpression Id. */
  int KW_AWAIT = 12;
  /** RegularExpression Id. */
  int KW_BREAK = 13;
  /** RegularExpression Id. */
  int KW_CONST = 14;
  /** RegularExpression Id. */
  int KW_CONTINUE = 15;
  /** RegularExpression Id. */
  int KW_CRATE = 16;
  /** RegularExpression Id. */
  int KW_DYN = 17;
  /** RegularExpression Id. */
  int KW_ELSE = 18;
  /** RegularExpression Id. */
  int KW_ENUM = 19;
  /** RegularExpression Id. */
  int KW_EXTERN = 20;
  /** RegularExpression Id. */
  int KW_FALSE = 21;
  /** RegularExpression Id. */
  int KW_FN = 22;
  /** RegularExpression Id. */
  int KW_FOR = 23;
  /** RegularExpression Id. */
  int KW_IF = 24;
  /** RegularExpression Id. */
  int KW_IMPL = 25;
  /** RegularExpression Id. */
  int KW_IN = 26;
  /** RegularExpression Id. */
  int KW_LET = 27;
  /** RegularExpression Id. */
  int KW_LOOP = 28;
  /** RegularExpression Id. */
  int KW_MATCH = 29;
  /** RegularExpression Id. */
  int KW_MOD = 30;
  /** RegularExpression Id. */
  int KW_MOVE = 31;
  /** RegularExpression Id. */
  int KW_MUT = 32;
  /** RegularExpression Id. */
  int KW_PUB = 33;
  /** RegularExpression Id. */
  int KW_REF = 34;
  /** RegularExpression Id. */
  int KW_RETURN = 35;
  /** RegularExpression Id. */
  int KW_SELF_LOWER = 36;
  /** RegularExpression Id. */
  int KW_SELF_UPPER = 37;
  /** RegularExpression Id. */
  int KW_STATIC = 38;
  /** RegularExpression Id. */
  int KW_STRUCT = 39;
  /** RegularExpression Id. */
  int KW_SUPER = 40;
  /** RegularExpression Id. */
  int KW_TRAIT = 41;
  /** RegularExpression Id. */
  int KW_TRUE = 42;
  /** RegularExpression Id. */
  int KW_TYPE = 43;
  /** RegularExpression Id. */
  int KW_UNSAFE = 44;
  /** RegularExpression Id. */
  int KW_USE = 45;
  /** RegularExpression Id. */
  int KW_WHERE = 46;
  /** RegularExpression Id. */
  int KW_WHILE = 47;
  /** RegularExpression Id. */
  int KW_ABSTRACT = 48;
  /** RegularExpression Id. */
  int KW_BECOME = 49;
  /** RegularExpression Id. */
  int KW_BOX = 50;
  /** RegularExpression Id. */
  int KW_DO = 51;
  /** RegularExpression Id. */
  int KW_FINAL = 52;
  /** RegularExpression Id. */
  int KW_GEN = 53;
  /** RegularExpression Id. */
  int KW_MACRO = 54;
  /** RegularExpression Id. */
  int KW_OVERRIDE = 55;
  /** RegularExpression Id. */
  int KW_PRIV = 56;
  /** RegularExpression Id. */
  int KW_TRY = 57;
  /** RegularExpression Id. */
  int KW_TYPEOF = 58;
  /** RegularExpression Id. */
  int KW_UNSIZED = 59;
  /** RegularExpression Id. */
  int KW_VIRTUAL = 60;
  /** RegularExpression Id. */
  int KW_YIELD = 61;
  /** RegularExpression Id. */
  int KW_UNION = 62;
  /** RegularExpression Id. */
  int KW_MACRO_RULES = 63;
  /** RegularExpression Id. */
  int KW_SAFE = 64;
  /** RegularExpression Id. */
  int KW_RAW = 65;
  /** RegularExpression Id. */
  int LIT_FLOAT = 66;
  /** RegularExpression Id. */
  int LIT_INT_BIN = 67;
  /** RegularExpression Id. */
  int LIT_INT_OCT = 68;
  /** RegularExpression Id. */
  int LIT_INT_HEX = 69;
  /** RegularExpression Id. */
  int LIT_INT_DEC = 70;
  /** RegularExpression Id. */
  int DEC_LIT = 71;
  /** RegularExpression Id. */
  int FLOAT_EXP = 72;
  /** RegularExpression Id. */
  int SUFFIX = 73;
  /** RegularExpression Id. */
  int LIT_CHAR = 74;
  /** RegularExpression Id. */
  int LIT_STRING = 75;
  /** RegularExpression Id. */
  int CHAR_ESCAPE = 76;
  /** RegularExpression Id. */
  int LIT_BYTE = 77;
  /** RegularExpression Id. */
  int LIT_BYTE_STRING = 78;
  /** RegularExpression Id. */
  int BYTE_ESCAPE = 79;
  /** RegularExpression Id. */
  int LIT_RAW_STRING = 80;
  /** RegularExpression Id. */
  int LIT_RAW_BYTE_STRING = 81;
  /** RegularExpression Id. */
  int LIFETIME = 82;
  /** RegularExpression Id. */
  int ID = 83;
  /** RegularExpression Id. */
  int RAW_ID = 84;
  /** RegularExpression Id. */
  int DOTDOTDOT = 85;
  /** RegularExpression Id. */
  int DOTDOTEQ = 86;
  /** RegularExpression Id. */
  int SHLEQ = 87;
  /** RegularExpression Id. */
  int SHREQ = 88;
  /** RegularExpression Id. */
  int BANGEQ = 89;
  /** RegularExpression Id. */
  int PERCENTEQ = 90;
  /** RegularExpression Id. */
  int AMPAMP = 91;
  /** RegularExpression Id. */
  int AMPEQ = 92;
  /** RegularExpression Id. */
  int STAREQ = 93;
  /** RegularExpression Id. */
  int PLUSEQ = 94;
  /** RegularExpression Id. */
  int MINUSEQ = 95;
  /** RegularExpression Id. */
  int ARROW = 96;
  /** RegularExpression Id. */
  int DOTDOT = 97;
  /** RegularExpression Id. */
  int SLASHEQ = 98;
  /** RegularExpression Id. */
  int COLONCOLON = 99;
  /** RegularExpression Id. */
  int SHL = 100;
  /** RegularExpression Id. */
  int LE = 101;
  /** RegularExpression Id. */
  int EQEQ = 102;
  /** RegularExpression Id. */
  int FATARROW = 103;
  /** RegularExpression Id. */
  int GE = 104;
  /** RegularExpression Id. */
  int SHR = 105;
  /** RegularExpression Id. */
  int CARETEQ = 106;
  /** RegularExpression Id. */
  int PIPEEQ = 107;
  /** RegularExpression Id. */
  int PIPEPIPE = 108;
  /** RegularExpression Id. */
  int BANG = 109;
  /** RegularExpression Id. */
  int HASH = 110;
  /** RegularExpression Id. */
  int DOLLAR = 111;
  /** RegularExpression Id. */
  int PERCENT = 112;
  /** RegularExpression Id. */
  int AMP = 113;
  /** RegularExpression Id. */
  int LPAREN = 114;
  /** RegularExpression Id. */
  int RPAREN = 115;
  /** RegularExpression Id. */
  int STAR = 116;
  /** RegularExpression Id. */
  int PLUS = 117;
  /** RegularExpression Id. */
  int COMMA = 118;
  /** RegularExpression Id. */
  int MINUS = 119;
  /** RegularExpression Id. */
  int DOT = 120;
  /** RegularExpression Id. */
  int SLASH = 121;
  /** RegularExpression Id. */
  int COLON = 122;
  /** RegularExpression Id. */
  int SEMI = 123;
  /** RegularExpression Id. */
  int LT = 124;
  /** RegularExpression Id. */
  int EQ = 125;
  /** RegularExpression Id. */
  int GT = 126;
  /** RegularExpression Id. */
  int QUESTION = 127;
  /** RegularExpression Id. */
  int AT = 128;
  /** RegularExpression Id. */
  int LBRACKET = 129;
  /** RegularExpression Id. */
  int BACKSLASH = 130;
  /** RegularExpression Id. */
  int RBRACKET = 131;
  /** RegularExpression Id. */
  int CARET = 132;
  /** RegularExpression Id. */
  int LBRACE = 133;
  /** RegularExpression Id. */
  int PIPE = 134;
  /** RegularExpression Id. */
  int RBRACE = 135;
  /** RegularExpression Id. */
  int TILDE = 136;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_BLOCK_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"as\"",
    "\"async\"",
    "\"await\"",
    "\"break\"",
    "\"const\"",
    "\"continue\"",
    "\"crate\"",
    "\"dyn\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"false\"",
    "\"fn\"",
    "\"for\"",
    "\"if\"",
    "\"impl\"",
    "\"in\"",
    "\"let\"",
    "\"loop\"",
    "\"match\"",
    "\"mod\"",
    "\"move\"",
    "\"mut\"",
    "\"pub\"",
    "\"ref\"",
    "\"return\"",
    "\"self\"",
    "\"Self\"",
    "\"static\"",
    "\"struct\"",
    "\"super\"",
    "\"trait\"",
    "\"true\"",
    "\"type\"",
    "\"unsafe\"",
    "\"use\"",
    "\"where\"",
    "\"while\"",
    "\"abstract\"",
    "\"become\"",
    "\"box\"",
    "\"do\"",
    "\"final\"",
    "\"gen\"",
    "\"macro\"",
    "\"override\"",
    "\"priv\"",
    "\"try\"",
    "\"typeof\"",
    "\"unsized\"",
    "\"virtual\"",
    "\"yield\"",
    "\"union\"",
    "\"macro_rules\"",
    "\"safe\"",
    "\"raw\"",
    "<LIT_FLOAT>",
    "<LIT_INT_BIN>",
    "<LIT_INT_OCT>",
    "<LIT_INT_HEX>",
    "<LIT_INT_DEC>",
    "<DEC_LIT>",
    "<FLOAT_EXP>",
    "<SUFFIX>",
    "<LIT_CHAR>",
    "<LIT_STRING>",
    "<CHAR_ESCAPE>",
    "<LIT_BYTE>",
    "<LIT_BYTE_STRING>",
    "<BYTE_ESCAPE>",
    "<LIT_RAW_STRING>",
    "<LIT_RAW_BYTE_STRING>",
    "<LIFETIME>",
    "<ID>",
    "<RAW_ID>",
    "\"...\"",
    "\"..=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"!=\"",
    "\"%=\"",
    "\"&&\"",
    "\"&=\"",
    "\"*=\"",
    "\"+=\"",
    "\"-=\"",
    "\"->\"",
    "\"..\"",
    "\"/=\"",
    "\"::\"",
    "\"<<\"",
    "\"<=\"",
    "\"==\"",
    "\"=>\"",
    "\">=\"",
    "\">>\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"!\"",
    "\"#\"",
    "\"$\"",
    "\"%\"",
    "\"&\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"?\"",
    "\"@\"",
    "\"[\"",
    "\"\\\\\"",
    "\"]\"",
    "\"^\"",
    "\"{\"",
    "\"|\"",
    "\"}\"",
    "\"~\"",
  };

}
