/* RustLexer.java */
/* Generated By:JavaCC: Do not edit this line. RustLexer.java */
import java.io.*;
import java.lang.reflect.*;

public class RustLexer implements RustLexerConstants {

    /* Mapa: kind → nome da classe em MAIÚSCULO */
    private static String[] classNames;

    private static void buildClassNames() {
        classNames = new String[tokenImage.length];

        /* Usa reflection para obter o nome do campo constante
           a partir do valor inteiro do kind */
        try {
            Field[] fields = RustLexerConstants.class.getDeclaredFields();
            for (Field f : fields) {
                if (f.getType() == int.class &&
                    Modifier.isStatic(f.getModifiers()) &&
                    Modifier.isFinal(f.getModifiers())) {
                    int val = f.getInt(null);
                    if (val >= 0 && val < classNames.length) {
                        classNames[val] = f.getName();
                    }
                }
            }
        } catch (Exception e) {
            /* fallback: se reflection falhar, usa tokenImage */
            for (int i = 0; i < tokenImage.length; i++) {
                String img = tokenImage[i];
                if (img.startsWith("<") && img.endsWith(">")) {
                    classNames[i] = img.substring(1, img.length() - 1);
                } else {
                    classNames[i] = img.replace("\"", "");
                }
            }
        }

        /* Preenche posicoes que ficaram null (ex: EOF) */
        for (int i = 0; i < classNames.length; i++) {
            if (classNames[i] == null) {
                String img = tokenImage[i];
                if (img.startsWith("<") && img.endsWith(">")) {
                    classNames[i] = img.substring(1, img.length() - 1);
                } else {
                    classNames[i] = img.replace("\"", "");
                }
            }
        }
    }

    public static void main(String[] args) throws ParseException, TokenMgrError {
        Reader reader;
        if (args.length > 0) {
            try {
                reader = new FileReader(args[0]);
            } catch (FileNotFoundException e) {
                System.err.println("Arquivo nao encontrado: " + args[0]);
                return;
            }
        } else {
            reader = new InputStreamReader(System.in);
        }

        RustLexer lexer = new RustLexer(reader);
        buildClassNames();

        Token t;
        while (true) {
            try {
                t = lexer.getNextToken();
            } catch (TokenMgrError e) {
                System.err.println("ERRO_LEXICO " + e.getMessage());
                return;
            }
            if (t.kind == EOF) break;

            /* Imprime comentários especiais que precedem este token */
            Token sp = t.specialToken;
            if (sp != null) {
                /* Percorre a lista encadeada até o início */
                while (sp.specialToken != null) sp = sp.specialToken;
                while (sp != null) {
                    printSpecial(sp);
                    sp = sp.next;
                }
            }

            System.out.println(classNames[t.kind] + " " + t.image);
        }
    }

    private static void printSpecial(Token sp) {
        String img = sp.image;
        if (img.startsWith("//")) {
            System.out.println("COMMENT_LINE " + img);
        } else if (img.startsWith("/*")) {
            System.out.println("COMMENT_BLOCK " + img);
        }
    }

  /** Generated Token Manager. */
  public RustLexerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	   jj_la1_init_3();
	   jj_la1_init_4();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {};
	}
	private static void jj_la1_init_3() {
	   jj_la1_3 = new int[] {};
	}
	private static void jj_la1_init_4() {
	   jj_la1_4 = new int[] {};
	}

  /** Constructor with InputStream. */
  public RustLexer(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RustLexer(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new RustLexerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public RustLexer(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new RustLexerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new RustLexerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Constructor with generated Token Manager. */
  public RustLexer(RustLexerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(RustLexerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[137];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		   if ((jj_la1_3[i] & (1<<j)) != 0) {
			 la1tokens[96+j] = true;
		   }
		   if ((jj_la1_4[i] & (1<<j)) != 0) {
			 la1tokens[128+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 137; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
